<?php
// $Id$

/**
 * @file dynamic_links.module
 */

/**
 * Implements hook_menu().
 */
function dynamic_links_menu() {
  $items['admin/dynamic_links'] = array(
    'title' => 'Dynamic links',
    'description' => 'Updated alias in the nodes.',
    'file' => 'dynamic_links.pages.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dynamic_links_update'),
    'access arguments' => array('access administration pages'),
  );

  return $items;
}

/**
 * Implements hook_nodeapi().
 */
function dynamic_links_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'update':
    case 'insert':
      module_load_include('inc', 'dynamic_links', 'dynamic_links');
      return dynamic_links_node_save($node);
  }
}

/**
 * Helper function for batch process.
 */
function _dynamic_links_node_save($nid, &$context) {
  if ($node = node_load($nid)) {
    $context['message']   = sprintf('Checking %s', $node->title);

    module_load_include('inc', 'dynamic_links', 'dynamic_links');
    dynamic_links_node_save($node);
  }
}
